import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navber/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"
import { Questrial } from 'next/font/google'

const questrial = Questrial({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Blog-Review",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${questrial.className} antialiased`}
        >
            <Navbar />
            <main className="container">
              {children}
            </main>
            <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
